// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkXu1RaJGeMNSa4G0LCa_LOf6V4AHHRo',
    appId: '1:641487561401:web:cb536436f1ca3db9417168',
    messagingSenderId: '641487561401',
    projectId: 'mosoon-9b9da',
    authDomain: 'mosoon-9b9da.firebaseapp.com',
    storageBucket: 'mosoon-9b9da.firebasestorage.app',
    measurementId: 'G-TSS9ZG5X5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9A8sX123OX5vGEUm0ZEvAkSpEBoKvobw',
    appId: '1:641487561401:android:aaae1f8e24213a21417168',
    messagingSenderId: '641487561401',
    projectId: 'mosoon-9b9da',
    storageBucket: 'mosoon-9b9da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALiICfsuEGmFo_bMu1mJgjIfL8SsPt4E',
    appId: '1:641487561401:ios:c00ab92f17d8d63c417168',
    messagingSenderId: '641487561401',
    projectId: 'mosoon-9b9da',
    storageBucket: 'mosoon-9b9da.firebasestorage.app',
    iosBundleId: 'com.mosoon.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCALiICfsuEGmFo_bMu1mJgjIfL8SsPt4E',
    appId: '1:641487561401:ios:c00ab92f17d8d63c417168',
    messagingSenderId: '641487561401',
    projectId: 'mosoon-9b9da',
    storageBucket: 'mosoon-9b9da.firebasestorage.app',
    iosBundleId: 'com.mosoon.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkXu1RaJGeMNSa4G0LCa_LOf6V4AHHRo',
    appId: '1:641487561401:web:2cad1b26ef7bb3cd417168',
    messagingSenderId: '641487561401',
    projectId: 'mosoon-9b9da',
    authDomain: 'mosoon-9b9da.firebaseapp.com',
    storageBucket: 'mosoon-9b9da.firebasestorage.app',
    measurementId: 'G-Z2RH4HCVF0',
  );
}
